Start testing: May 26 00:01 ART
----------------------------------------------------------
1/2 Testing: mockAuthenticationCtrlTest
1/2 Test: mockAuthenticationCtrlTest
Command: "/home/agustin/git/serverapp/AppServer/cmake/mockAuthenticationCtrlTest"
Directory: /home/agustin/git/serverapp/AppServer/cmake
"mockAuthenticationCtrlTest" start time: May 26 00:01 ART
Output:
----------------------------------------------------------
INFO - Iniciando Tests
[==========] Running 3 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 1 test from JwTokenTest
[ RUN      ] JwTokenTest.generatingToken
*****************************************************************
TOKEN GENERADO: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmUiOiI2MCIsInRpbWVzdGFtcCI6IjE0NjQyMzE2ODciLCJ1c2VybmFtZSI6InBzaXZvcmkifQ.p_pXwxqtn8KhSbbMm4J6TRsWFkwsim1ud3PC9aMpSB0
*****************************************************************
[       OK ] JwTokenTest.generatingToken (2 ms)
[----------] 1 test from JwTokenTest (2 ms total)

[----------] 1 test from AuthorizationTokenTest
[ RUN      ] AuthorizationTokenTest.isValidToken
[       OK ] AuthorizationTokenTest.isValidToken (0 ms)
[----------] 1 test from AuthorizationTokenTest (0 ms total)

[----------] 1 test from AuthenticationServiceTest
[ RUN      ] AuthenticationServiceTest.login
terminate called after throwing an instance of 'RemoteException'
  what():  el shared server retorno error
DEBUG - JSON: {"user":{"email":"","id":"","name":"psivori","password":"password","token":""}}

DEBUG - Password base password
DEBUG - Password ingresado password
DEBUG - Response code 400
DEBUG - Response body {"success":false,"data":"Invalid user ID"}
ERROR - El shared server retorno error
<end of output>
Test time =   0.76 sec
----------------------------------------------------------
Test Failed.
"mockAuthenticationCtrlTest" end time: May 26 00:01 ART
"mockAuthenticationCtrlTest" time elapsed: 00:00:00
----------------------------------------------------------

2/2 Testing: mockMatchServiceTest
2/2 Test: mockMatchServiceTest
Command: "/home/agustin/git/serverapp/AppServer/cmake/mockMatchServiceTest"
Directory: /home/agustin/git/serverapp/AppServer/cmake
"mockMatchServiceTest" start time: May 26 00:01 ART
Output:
----------------------------------------------------------
INFO - Iniciando Tests
[==========] Running 18 tests from 18 test cases.
[----------] Global test environment set-up.
[----------] 1 test from MatchServiceConfirmTest
[ RUN      ] MatchServiceConfirmTest.confirmingUser
INFO - Confirmando match con usuario alinari para usuario psivori

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: MockFunctionPut("psivori", 0x1e82d10)
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
[       OK ] MatchServiceConfirmTest.confirmingUser (0 ms)
[----------] 1 test from MatchServiceConfirmTest (0 ms total)

[----------] 1 test from MatchServiceConfirmBadUserTest
[ RUN      ] MatchServiceConfirmBadUserTest.confirmingBadUser
ERROR - Es el mismo usuario
[       OK ] MatchServiceConfirmBadUserTest.confirmingBadUser (1 ms)
[----------] 1 test from MatchServiceConfirmBadUserTest (1 ms total)

[----------] 1 test from MatchServiceConfirmUserIsInAcceptedListTest
[ RUN      ] MatchServiceConfirmUserIsInAcceptedListTest.confirmingUserIsInAcceptedList
ERROR - El usuario alinari ya se encuentra en la lista de aceptados
[       OK ] MatchServiceConfirmUserIsInAcceptedListTest.confirmingUserIsInAcceptedList (0 ms)
[----------] 1 test from MatchServiceConfirmUserIsInAcceptedListTest (0 ms total)

[----------] 1 test from MatchServiceConfirmUserIsInRejectedListTest
[ RUN      ] MatchServiceConfirmUserIsInRejectedListTest.confirmingUserIsInRejectedList
ERROR - El usuario alinari ya se encuentra en la lista de rechazados
[       OK ] MatchServiceConfirmUserIsInRejectedListTest.confirmingUserIsInRejectedList (0 ms)
[----------] 1 test from MatchServiceConfirmUserIsInRejectedListTest (0 ms total)

[----------] 1 test from MatchServiceConfirmUserIsNotMatchedTest
[ RUN      ] MatchServiceConfirmUserIsNotMatchedTest.confirmingUserIsNotMatched
[       OK ] MatchServiceConfirmUserIsNotMatchedTest.confirmingUserIsNotMatched (0 ms)
[----------] 1 test from MatchServiceConfirmUserIsNotMatchedTest (0 ms total)

[----------] 1 test from MatchServiceAccept1Test
[ RUN      ] MatchServiceAccept1Test.acceptingUser1

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getChat("psivori", "alinari")
          Returns: NULL
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
ERROR - Los usuarios ya estan matcheados
ERROR - La entidad ya existe
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:275: Failure
Expected: {res = matchService->addToYesList("psivori","alinari");} doesn't throw an exception.
  Actual: it throws.
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:272: Failure
Actual function call count doesn't match EXPECT_CALL(*mockMatchDao, MockFunctionPut("psivori", matchPsivori))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] MatchServiceAccept1Test.acceptingUser1 (2 ms)
[----------] 1 test from MatchServiceAccept1Test (2 ms total)

[----------] 1 test from MatchServiceAccept2Test
[ RUN      ] MatchServiceAccept2Test.acceptingUser2

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getChat("psivori", "alinari")
          Returns: NULL
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
ERROR - Los usuarios ya estan matcheados
ERROR - La entidad ya existe
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:296: Failure
Expected: {res = matchService->addToYesList("psivori","alinari");} doesn't throw an exception.
  Actual: it throws.
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:293: Failure
Actual function call count doesn't match EXPECT_CALL(*mockMatchDao, MockFunctionPut("psivori", matchPsivori))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] MatchServiceAccept2Test.acceptingUser2 (0 ms)
[----------] 1 test from MatchServiceAccept2Test (0 ms total)

[----------] 1 test from MatchServiceAcceptBadUserTest
[ RUN      ] MatchServiceAcceptBadUserTest.acceptingBadUser
ERROR - Es el mismo usuario
[       OK ] MatchServiceAcceptBadUserTest.acceptingBadUser (0 ms)
[----------] 1 test from MatchServiceAcceptBadUserTest (0 ms total)

[----------] 1 test from MatchServiceAcceptUserIsInRejectedListTest
[ RUN      ] MatchServiceAcceptUserIsInRejectedListTest.confirmingUserIsInRejectedList
ERROR - El usuario alinari ya se encuentra en la lista de rechazados
ERROR - La entidad ya existe
[       OK ] MatchServiceAcceptUserIsInRejectedListTest.confirmingUserIsInRejectedList (0 ms)
[----------] 1 test from MatchServiceAcceptUserIsInRejectedListTest (1 ms total)

[----------] 1 test from MatchServiceAcceptUserIsMatchedTest
[ RUN      ] MatchServiceAcceptUserIsMatchedTest.confirmingUserIsMatched

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getChat("psivori", "jferrio")
          Returns: NULL
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
ERROR - Los usuarios ya estan matcheados
ERROR - La entidad ya existe
[       OK ] MatchServiceAcceptUserIsMatchedTest.confirmingUserIsMatched (0 ms)
[----------] 1 test from MatchServiceAcceptUserIsMatchedTest (0 ms total)

[----------] 1 test from MatchServiceAcceptChatExistsTest
[ RUN      ] MatchServiceAcceptChatExistsTest.confirmingUserChatExists
ERROR - El usuario alinari ya se encuentra en la lista de matcheados
ERROR - La entidad ya existe
[       OK ] MatchServiceAcceptChatExistsTest.confirmingUserChatExists (0 ms)
[----------] 1 test from MatchServiceAcceptChatExistsTest (4 ms total)

[----------] 1 test from MatchServiceRejectTest
[ RUN      ] MatchServiceRejectTest.rejectingUser

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getChat("psivori", "alinari")
          Returns: NULL
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
ERROR - Los usuarios ya estan matcheados
ERROR - La entidad ya existe
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:414: Failure
Expected: {matchService->addToNoList("psivori","alinari");} doesn't throw an exception.
  Actual: it throws.
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:412: Failure
Actual function call count doesn't match EXPECT_CALL(*mockMatchDao, MockFunctionPut("psivori", match))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] MatchServiceRejectTest.rejectingUser (1 ms)
[----------] 1 test from MatchServiceRejectTest (1 ms total)

[----------] 1 test from MatchServiceRejectBadUserTest
[ RUN      ] MatchServiceRejectBadUserTest.rejectingBadUser
ERROR - Es el mismo usuario
[       OK ] MatchServiceRejectBadUserTest.rejectingBadUser (0 ms)
[----------] 1 test from MatchServiceRejectBadUserTest (0 ms total)

[----------] 1 test from MatchServiceRejectUserIsInAceptedListTest
[ RUN      ] MatchServiceRejectUserIsInAceptedListTest.rejectingUserIsInAceptedList
ERROR - El usuario alinari ya se encuentra en la lista de aceptados
ERROR - La entidad ya existe
[       OK ] MatchServiceRejectUserIsInAceptedListTest.rejectingUserIsInAceptedList (0 ms)
[----------] 1 test from MatchServiceRejectUserIsInAceptedListTest (0 ms total)

[----------] 1 test from MatchServiceRejectUserIsInRejectedListTest
[ RUN      ] MatchServiceRejectUserIsInRejectedListTest.rejectingUserIsInRejectedList
ERROR - El usuario alinari ya se encuentra en la lista de rechazados
[       OK ] MatchServiceRejectUserIsInRejectedListTest.rejectingUserIsInRejectedList (0 ms)
[----------] 1 test from MatchServiceRejectUserIsInRejectedListTest (0 ms total)

[----------] 1 test from MatchServiceRejectUserIsMatchedTest
[ RUN      ] MatchServiceRejectUserIsMatchedTest.rejectingUserIsMatched

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getChat("psivori", "jferrio")
          Returns: NULL
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
ERROR - Los usuarios ya estan matcheados
ERROR - La entidad ya existe
[       OK ] MatchServiceRejectUserIsMatchedTest.rejectingUserIsMatched (0 ms)
[----------] 1 test from MatchServiceRejectUserIsMatchedTest (4 ms total)

[----------] 1 test from MatchServiceRejectChatExistsTest
[ RUN      ] MatchServiceRejectChatExistsTest.rejectingUserChatExists
ERROR - El usuario alinari ya se encuentra en la lista de matcheados
ERROR - La entidad ya existe
[       OK ] MatchServiceRejectChatExistsTest.rejectingUserChatExists (1 ms)
[----------] 1 test from MatchServiceRejectChatExistsTest (1 ms total)

[----------] 1 test from MatchServiceTest
[ RUN      ] MatchServiceTest.getNewMatches
INFO - Obteniendo la lista de nuevos matches del usuario psivori
[       OK ] MatchServiceTest.getNewMatches (0 ms)
[----------] 1 test from MatchServiceTest (0 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 18 test cases ran. (14 ms total)
[  PASSED  ] 15 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] MatchServiceAccept1Test.acceptingUser1
[  FAILED  ] MatchServiceAccept2Test.acceptingUser2
[  FAILED  ] MatchServiceRejectTest.rejectingUser

 3 FAILED TESTS

/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:360: ERROR: this mock object (used in test MatchServiceAcceptUserIsMatchedTest.confirmingUserIsMatched) should be deleted but never is. Its address is @0x1e890a0.
/home/agustin/git/serverapp/AppServer/test/MockMatchService.cc:490: ERROR: this mock object (used in test MatchServiceRejectUserIsMatchedTest.rejectingUserIsMatched) should be deleted but never is. Its address is @0x1e8a2b0.
ERROR: 2 leaked mock objects found at program exit.
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"mockMatchServiceTest" end time: May 26 00:01 ART
"mockMatchServiceTest" time elapsed: 00:00:00
----------------------------------------------------------

End testing: May 26 00:01 ART
